spring.application.name=ProManage

# Security - Clerk
spring.security.oauth2.resourceserver.jwt.issuer-uri=${CLERK_ISSUER_URI}
spring.security.oauth2.resourceserver.jwt.audiences=${CLERK_AUDIENCE}

# Database - Neon
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Mail - Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Inngest
inngest.event.key=${INNGEST_EVENT_KEY}

# Connection Pooling
spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
spring.datasource.hikari.keepalive-time=30000