spring.application.name=ProManage

spring.security.oauth2.resourceserver.jwt.issuer-uri=https://nearby-halibut-71.clerk.accounts.dev
spring.security.oauth2.resourceserver.jwt.audiences=spring-boot-api

spring.datasource.url=jdbc:postgresql://ep-noisy-shadow-a16qc0s4-pooler.ap-southeast-1.aws.neon.tech/neondb?user=neondb_owner&password=npg_IvpU0XHPG9sT&sslmode=require&channelBinding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_IvpU0XHPG9sT

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mahawar20031203@gmail.com
spring.mail.password=jxscgtovqlqwvgjw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
logging.level.org.springframework.mail=DEBUG
logging.level.javax.mail=DEBUG


inngest.event.key=IwpSLvKW4JKzRnJ9HC6ZVS4kGbYlizhWt_YVe2zqJHSQZwRunhb0anEesny4lHFZLuwGydjfPF84-Q-M3OLshA

spring.datasource.hikari.max-lifetime=600000
spring.datasource.hikari.idle-timeout=300000
spring.datasource.hikari.connection-timeout=20000
# This ensures Spring tests the connection before trying to use it
spring.datasource.hikari.keepalive-time=30000